trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
  workingDirectory: eth-nft-poc/

- script: |
    npx hardhat compile
  displayName: 'hardhat compile'
  workingDirectory: eth-nft-poc/

- script: |
    npx hardhat test
  displayName: 'hardhat test'
  workingDirectory: eth-nft-poc/
