trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
  workingDirectory: eth-nft-poc/

- script: |
    npx hardhat compile
  displayName: 'hardhat compile'
  workingDirectory: eth-nft-poc/

- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: |
      npm install -g npx
      npx hardhat test
    verbose: true
    customCommand: 'install npx'
    workingDirectory: eth-nft-poc/

# - script: |
#     npm install npx
#     npx hardhat test
#   displayName: 'hardhat test'
#   workingDirectory: eth-nft-poc/
