trigger:
- pipeline

pool:
  vmImage: ubuntu-latest

container: node:18-bullseye-slim@sha256:f32c970581a901560815b9af1aebbc164c86b9be922dda3b9f3b65f653e61776

variables:
- name: poc-directory
  value: eth-nft-poc

steps:
- script: |
    npm install
  displayName: 'npm install'
  workingDirectory: $(poc-directory)

- script: |
    npx hardhat compile
  displayName: 'Compile smart contracts'
  workingDirectory: $(poc-directory)

- script: |
    npx hardhat test
  displayName: 'Test smart contracts'
  workingDirectory: $(poc-directory)

# - task: PublishHtmlReport@1
#   displayName: 'Publish coverage report'
#   inputs:
#     reportDir: '$(poc-directory)/coverage/index.html'
